---
version: '3.7'

services:
  rbox:
    build:
      context: .
    image: rbox:0.0.3
    volumes:
      - type: volume
        source: z3nbox
        target: /home/rbox/.ssh
    networks:
      - rbox-external-net
    ports:
      - "50051:50051"

  rbox-dev:
    build:
      context: .
      target: devel
    image: rbox-dev:0.0.3
    volumes:
      - type: bind
        source: .
        target: /go/src/github.com/ronaldoafonso/rbox
      - type: bind
        source: ./rbox/uci
        target: /home/rbox/uci
      - type: volume
        source: z3nbox
        target: /home/rbox/.ssh
    networks:
      - rbox-external-net
    ports:
      - "50051:50051"
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]

volumes:
  z3nbox:
    name: z3nbox

networks:
  rbox-external-net:
    name: rbox-external-net
...
