// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gcommand

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RemoteCommandClient is the client API for RemoteCommand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteCommandClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ReturnMsg, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*ReturnMsg, error)
}

type remoteCommandClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteCommandClient(cc grpc.ClientConnInterface) RemoteCommandClient {
	return &remoteCommandClient{cc}
}

func (c *remoteCommandClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*ReturnMsg, error) {
	out := new(ReturnMsg)
	err := c.cc.Invoke(ctx, "/gcommand.RemoteCommand/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteCommandClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*ReturnMsg, error) {
	out := new(ReturnMsg)
	err := c.cc.Invoke(ctx, "/gcommand.RemoteCommand/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteCommandServer is the server API for RemoteCommand service.
// All implementations must embed UnimplementedRemoteCommandServer
// for forward compatibility
type RemoteCommandServer interface {
	Get(context.Context, *GetRequest) (*ReturnMsg, error)
	Set(context.Context, *SetRequest) (*ReturnMsg, error)
	mustEmbedUnimplementedRemoteCommandServer()
}

// UnimplementedRemoteCommandServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteCommandServer struct {
}

func (UnimplementedRemoteCommandServer) Get(context.Context, *GetRequest) (*ReturnMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRemoteCommandServer) Set(context.Context, *SetRequest) (*ReturnMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRemoteCommandServer) mustEmbedUnimplementedRemoteCommandServer() {}

// UnsafeRemoteCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteCommandServer will
// result in compilation errors.
type UnsafeRemoteCommandServer interface {
	mustEmbedUnimplementedRemoteCommandServer()
}

func RegisterRemoteCommandServer(s grpc.ServiceRegistrar, srv RemoteCommandServer) {
	s.RegisterService(&RemoteCommand_ServiceDesc, srv)
}

func _RemoteCommand_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCommandServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gcommand.RemoteCommand/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCommandServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteCommand_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCommandServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gcommand.RemoteCommand/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCommandServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteCommand_ServiceDesc is the grpc.ServiceDesc for RemoteCommand service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteCommand_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gcommand.RemoteCommand",
	HandlerType: (*RemoteCommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RemoteCommand_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _RemoteCommand_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gcommand.proto",
}
