// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: gcommand.proto

package gcommand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxname string `protobuf:"bytes,1,opt,name=Boxname,proto3" json:"Boxname,omitempty"`
	Field   string `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_gcommand_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetBoxname() string {
	if x != nil {
		return x.Boxname
	}
	return ""
}

func (x *GetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boxname string `protobuf:"bytes,1,opt,name=Boxname,proto3" json:"Boxname,omitempty"`
	Field   string `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gcommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_gcommand_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequest) GetBoxname() string {
	if x != nil {
		return x.Boxname
	}
	return ""
}

func (x *SetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReturnMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnMsg string `protobuf:"bytes,1,opt,name=returnMsg,proto3" json:"returnMsg,omitempty"`
}

func (x *ReturnMsg) Reset() {
	*x = ReturnMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gcommand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnMsg) ProtoMessage() {}

func (x *ReturnMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gcommand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnMsg.ProtoReflect.Descriptor instead.
func (*ReturnMsg) Descriptor() ([]byte, []int) {
	return file_gcommand_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnMsg) GetReturnMsg() string {
	if x != nil {
		return x.ReturnMsg
	}
	return ""
}

var File_gcommand_proto protoreflect.FileDescriptor

var file_gcommand_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6f, 0x78, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x6f, 0x78, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x52, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x6f, 0x78, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x42, 0x6f, 0x78, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x09,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x32, 0x77, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x14, 0x2e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03,
	0x53, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x73, 0x67, 0x22, 0x00,
	0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x6f, 0x6e, 0x61, 0x6c, 0x64, 0x6f, 0x61, 0x66, 0x6f, 0x6e, 0x73, 0x6f, 0x2f, 0x72, 0x62, 0x6f,
	0x78, 0x2f, 0x67, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gcommand_proto_rawDescOnce sync.Once
	file_gcommand_proto_rawDescData = file_gcommand_proto_rawDesc
)

func file_gcommand_proto_rawDescGZIP() []byte {
	file_gcommand_proto_rawDescOnce.Do(func() {
		file_gcommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_gcommand_proto_rawDescData)
	})
	return file_gcommand_proto_rawDescData
}

var file_gcommand_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gcommand_proto_goTypes = []interface{}{
	(*GetRequest)(nil), // 0: gcommand.GetRequest
	(*SetRequest)(nil), // 1: gcommand.SetRequest
	(*ReturnMsg)(nil),  // 2: gcommand.ReturnMsg
}
var file_gcommand_proto_depIdxs = []int32{
	0, // 0: gcommand.RemoteCommand.Get:input_type -> gcommand.GetRequest
	1, // 1: gcommand.RemoteCommand.Set:input_type -> gcommand.SetRequest
	2, // 2: gcommand.RemoteCommand.Get:output_type -> gcommand.ReturnMsg
	2, // 3: gcommand.RemoteCommand.Set:output_type -> gcommand.ReturnMsg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gcommand_proto_init() }
func file_gcommand_proto_init() {
	if File_gcommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gcommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gcommand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gcommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gcommand_proto_goTypes,
		DependencyIndexes: file_gcommand_proto_depIdxs,
		MessageInfos:      file_gcommand_proto_msgTypes,
	}.Build()
	File_gcommand_proto = out.File
	file_gcommand_proto_rawDesc = nil
	file_gcommand_proto_goTypes = nil
	file_gcommand_proto_depIdxs = nil
}
